export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORY_FAIL = 'CATEGORY_FAIL';
export const CATEGORY_RESET = 'CATEGORY_RESET';

export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
