export const BATCH_REQUEST = 'BATCH_REQUEST';
export const BATCH_FAIL = 'BATCH_FAIL';
export const BATCH_RESET = 'BATCH_RESET';

export const CREATE_BATCH_SUCCESS = 'CREATE_BATCH_SUCCESS';
export const GET_BATCHES_SUCCESS = 'GET_BATCHES_SUCCESS';
export const GET_BATCH_SUCCESS = 'GET_BATCH_SUCCESS';
export const UPDATE_BATCH_SUCCESS = 'UPDATE_BATCH_SUCCESS';
