export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAIL = 'USER_FAIL';
export const USER_RESET = 'USER_RESET';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
