export const PLATFORM_REQUEST = 'PLATFORM_REQUEST';
export const PLATFORM_FAIL = 'PLATFORM_FAIL';
export const PLATFORM_RESET = 'PLATFORM_RESET';
export const GET_PLATFORM_SUCCESS = 'GET_PLATFORM_SUCCESS';
export const CREATE_PLATFORM_SUCCESS = 'CREATE_PLATFORM_SUCCESS';
export const UPDATE_PLATFORM_SUCCESS = 'UPDATE_PLATFORM_SUCCESS';
